security:
  oauth2:
    client:
      clientId: <Enter your App ID>
      client-secret: <Enter Your App Secret Code>
      access-token-uri: https://graph.facebook.com/oauth/access_token
      user-authorization-uri: https://www.facebook.com/dialog/oauth
      token-name: oauth_token
      authentication-scheme: form
    resource:
      user-info-uri: https://graph.facebook.com/mem
server:
  port: 8081
